/**
 * SSE (Server-Sent Events) Module - Public API
 *
 * Provides workflow event broadcasting capabilities for real-time client updates.
 * Integrates with DBOS workflows to emit SSE events when steps complete or fail.
 *
 * Usage pattern:
 * 1. Workflows call broadcastWorkflowEvent() after each step
 * 2. Workflows call closeWorkflowSubscriptions() on terminal state
 * 3. SSE clients connect via /api/workflows/[id]/subscribe endpoint
 * 4. Events flow from workflow → subscription manager → SSE clients
 */

import { getSubscriptionManager as getManagerSingleton } from './WorkflowSubscriptionManager';
import { getWorkflowContext } from '../context';
import type {
  WorkflowEvent,
  WorkflowEventType,
  SSEEventPayload,
  EventSubscription,
  EventPayload
} from './types';

// ============================================================================
// Re-exports
// ============================================================================

/**
 * Get the global WorkflowSubscriptionManager instance
 *
 * Singleton that manages SSE subscriptions and event broadcasting.
 * Used by SSE endpoint to register client connections.
 */
export { getSubscriptionManager } from './WorkflowSubscriptionManager';

/**
 * Type definitions for SSE events and subscriptions
 */
export type {
  WorkflowEvent,
  WorkflowEventType,
  SSEEventPayload,
  EventSubscription,
  EventPayload
} from './types';

// ============================================================================
// Event Broadcasting Helper
// ============================================================================

/**
 * Broadcast a workflow event to all connected SSE clients
 *
 * Fire-and-forget pattern: Does NOT throw on errors. Failures are logged but
 * don't block workflow execution. Use this after each workflow step completes
 * or fails to notify clients in real-time.
 *
 * Requires:
 * - Must be called within a workflow execution context (WorkflowContext set)
 * - WorkflowContext provides workflowId and stepName automatically
 *
 * @param workflowId - DBOS workflow UUID
 * @param stepName - Name of the workflow step (e.g., "intakeStep", "ideationStep")
 * @param eventType - Event discriminator (step:started/completed/failed, workflow:error)
 * @param payload - Event payload with output, cost, error data
 * @param durationMs - Optional duration in milliseconds (for completed/failed events)
 *
 * @example
 * ```typescript
 * // After step completes successfully
 * const stepStartTime = Date.now();
 * const result = await DBOS.runStep(() => AgentExecutor.execute(...), { name: 'intakeStep' });
 * const stepDuration = Date.now() - stepStartTime;
 *
 * await broadcastWorkflowEvent(
 *   workflowId,
 *   'intakeStep',
 *   'step:completed',
 *   {
 *     output: result.output.substring(0, 200), // Truncate per D022
 *     tokensUsed: result.tokensUsed,
 *     costUsd: result.costUsd
 *   },
 *   stepDuration
 * );
 * ```
 *
 * @example
 * ```typescript
 * // On step failure
 * try {
 *   const result = await DBOS.runStep(() => AgentExecutor.execute(...), { name: 'intakeStep' });
 * } catch (error) {
 *   await broadcastWorkflowEvent(
 *     workflowId,
 *     'intakeStep',
 *     'step:failed',
 *     { error: String(error) },
 *     Date.now() - stepStartTime
 *   );
 *   throw error;
 * }
 * ```
 */
export async function broadcastWorkflowEvent(
  workflowId: string,
  stepName: string,
  eventType: WorkflowEventType,
  payload: EventPayload,
  durationMs?: number
): Promise<void> {
  try {
    // Validate we're in a workflow context
    const context = getWorkflowContext();
    const currentContext = context.getCurrentContext();

    if (!currentContext) {
      // Not in workflow context - this is likely a coding error
      // Log but don't throw (fire and forget)
      console.warn(
        `[SSE] broadcastWorkflowEvent called outside workflow context: ${workflowId}/${stepName}/${eventType}`
      );
      // Continue anyway - some callers may not have context set
    }

    // Create event object (without sequenceNumber - manager adds it)
    const event: Omit<WorkflowEvent, 'sequenceNumber'> = {
      workflowId,
      stepName,
      eventType,
      timestamp: new Date().toISOString(),
      durationMs,
      payload
    };

    // Broadcast to all subscribers
    // sequenceNumber is auto-generated by subscription manager
    const manager = getManagerSingleton();
    manager.broadcast(workflowId, event);

    // Fire and forget - no error propagation
  } catch (error) {
    // Silently log errors - don't block workflow execution
    console.error(
      `[SSE] Failed to broadcast event: ${workflowId}/${stepName}/${eventType}`,
      error
    );
    // Do NOT throw - fire and forget pattern
  }
}

// ============================================================================
// Terminal State Handler
// ============================================================================

/**
 * Close all SSE subscriptions for a workflow
 *
 * Call this when workflow reaches terminal state (SUCCESS/ERROR/CANCELLED)
 * to clean up memory and close client connections gracefully.
 *
 * IMPORTANT: Must be called to prevent memory leaks. The subscription manager
 * does NOT automatically clean up subscriptions when workflows complete.
 *
 * This function:
 * - Removes all subscription callbacks for the workflow
 * - Resets the sequence counter
 * - Triggers connection cleanup on SSE endpoint (via request.signal.abort)
 *
 * @param workflowId - DBOS workflow UUID
 *
 * @example
 * ```typescript
 * try {
 *   // Execute workflow steps
 *   const result = await executeWorkflowSteps();
 *   return result;
 * } catch (error) {
 *   await broadcastWorkflowEvent(workflowId, 'workflow', 'workflow:error', { error: String(error) });
 *   throw error;
 * } finally {
 *   // Always close subscriptions on terminal state
 *   closeWorkflowSubscriptions(workflowId);
 * }
 * ```
 */
export function closeWorkflowSubscriptions(workflowId: string): void {
  try {
    const manager = getManagerSingleton();
    manager.clear(workflowId);
  } catch (error) {
    // Log but don't throw - cleanup should not fail workflow
    console.error(
      `[SSE] Failed to close subscriptions for workflow ${workflowId}`,
      error
    );
  }
}
